/********************************************************************************************************
*** Create DBA database - SQL2017
***
*** Creates a 1GB DBA database. SQL2017 specific (database scoped configuration)
*** Assumes standard drive letters (D for data, L for log)
***
*** Ver		Date		Author
*** 1.0		08/11/19	Alex Stuart
***
*********************************************************************************************************/
USE [master]
GO

CREATE DATABASE [DBA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBS_Maintenance', FILENAME = N'D:\MSSQL\Data\DBA.mdf' , SIZE = 1048576KB , MAXSIZE = UNLIMITED, FILEGROWTH = 524288KB ), 
 FILEGROUP [DATA]  DEFAULT
( NAME = N'DBS_Maintenance_1', FILENAME = N'D:\MSSQL\Data\DBA.ndf' , SIZE = 1048576KB , MAXSIZE = UNLIMITED, FILEGROWTH = 524288KB )
 LOG ON 
( NAME = N'DBS_Maintenance_log', FILENAME = N'L:\MSSQL\Log\DBA.ldf' , SIZE = 524288KB , MAXSIZE = 2048GB , FILEGROWTH = 131072KB )
GO

ALTER DATABASE [DBA] MODIFY FILEGROUP [DATA] AUTOGROW_ALL_FILES
GO

ALTER DATABASE [DBA] MODIFY FILEGROUP [PRIMARY] AUTOGROW_ALL_FILES
GO

ALTER DATABASE [DBA] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBA] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBA] SET RECOVERY FULL 
GO

ALTER DATABASE [DBA] SET  MULTI_USER 
GO

ALTER DATABASE [DBA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DBA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBA] SET QUERY_STORE = OFF
GO

USE [DBA]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 4;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = ON;
GO

ALTER DATABASE [DBA] SET  READ_WRITE 
GO


